repos:

  - repo: local
    hooks:
      - id: system-ruff
        name: System Ruff Check
        entry: bash -c 'python -m ruff check .'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: system-mypy
        name: System Mypy
        entry: bash -c 'python -m mypy splurge_vendor_sync'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        
      - id: system-pytest
        name: System Pytest
        entry: bash -c 'python -m pytest -q'
        language: system
        pass_filenames: false
        stages: [pre-commit]
